fix relase final

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -3,7 +3,7 @@ name: Release
 on:
   push:
     tags:
-      - "v*"
+      - "*"
 
 permissions:
   contents: write
@@ -13,25 +13,28 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+      - uses: actions/checkout@v4
 
-      - name: Setup Node
-        uses: actions/setup-node@v4
+      - uses: actions/setup-node@v4
         with:
-          node-version: 22
+          node-version: 20
           cache: npm
 
-      - name: Install dependencies
-        run: npm ci
+      - run: npm ci
 
-      - name: Build Vite app
-        run: npm run build
+      - name: Build
+        run: |
+          npm run build
+          ls -lah
+          ls -lah dist || echo "NO DIST"
 
-      - name: Zip dist folder
-        run: zip -r dist.zip dist
+      - name: Zip
+        run: |
+          test -d dist || (echo "dist missing" && exit 1)
+          zip -r dist.zip dist
+          ls -lah dist.zip
 
-      - name: Create GitHub Release + upload asset
+      - name: Release
         uses: softprops/action-gh-release@v2
         with:
           files: dist.zip
